### ISSUE TITLE
Normal queries

### ISSUE THREAD

**Issue by Tim-Wils** [mardix/VoodOrm#1]
Hello!

I'm having issues with doing a normal query here.
The problem is: the result is giving back the rows ordered by id, instead of the order given in the query.

$result = $this->query("
            SELECT p1.*
            FROM 
                pages p1
            LEFT JOIN 
                pages p2
            ON 
                p1.parent_id = p2.id
            LEFT JOIN 
                pages p3
            ON 
                p2.parent_id = p3.id
            ORDER BY
                CASE 
                    WHEN 
                        p1.parent_id = 0
                    THEN 
                        p1.id
                    WHEN 
                        p2.parent_id = p3.id 
                    THEN 
                        p2.parent_id 
                    ELSE 
                        p1.parent_id
                END,
                p1.parent_id
            ")->find();

I think the bug has something to do with the find() method and the $is_fluent_query.

I just wanted a normal query to work :-)

**Comment by mardix** [comment]
When you were running find() after select(), it actually executed a new query. It's fixed now. Thank you
