### ISSUE TITLE
Great Idea but doesn't work

### ISSUE THREAD

**Issue by gmilby** [mardix/VoodOrm#2]
followed your readme - doesn't work/500 errors

$pdo = new PDO("mysql:host=localhost;dbname=$dbname", $username, $password);
$DB = new VoodOrm($pdo);
VoodOrm VoodOrm::table( string $tablename )
To connect to a table is straight forward by calling the method VoodOrm::table()
$users = $DB->table('users');

did something change - readme/tut not updated?
tia,

**Comment by mardix** [comment]
Can you please send me a sample of your code to see exactly what's going on?

Thanks
